# Generated by Django 5.2.6 on 2025-09-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('در حال انتظار', 'در حال انتظار'), ('اتمام شد', 'اتمام شد'), ('لغو', 'لفو')], default='در حال انتظار', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
