# Generated by Django 5.2.6 on 2025-10-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wait', '0002_wait_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wait',
            name='facility',
            field=models.CharField(choices=[('ساده', 'ساده'), ('با پریز', 'با پریز')], default='ساده', max_length=20),
        ),
    ]
