# Generated by Django 5.2.6 on 2025-09-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=1, upload_to='menu/images/'),
            preserve_default=False,
        ),
    ]
