# Generated by Django 5.2.6 on 2025-09-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ثبت شده', 'ثبت شده'), ('در حال تهیه', 'در حال تهیه'), ('تهیه شده', 'تهیه شده'), ('تحویل داده شد', 'تحویل داده شد')], default='ثبت شده', max_length=20),
        ),
    ]
